### ISSUE TITLE
Requires output file to already exsist

### ISSUE THREAD

**Issue by wilsonjord** [ohdatboi/profdump#1]
> profdump -d trace.log output.txt
File 'output.txt' does not exist

From the source code:
			if(exists(args[2])) {
				output = File(args[2], "w");
			} else {
				stderr.writefln("File '%s' does not exist", args[2]);
				return help(result);
			}

Since file mode is "w", probably no need for function exists at all?

**Comment by AntonMeep** [comment]
Oops! I fixed this and added `-f` option which forces profdump to overwrite output file.
